#!/usr/bin/env groovy

node() {
    stage('checkout') {
        cleanWs()
        checkout scm
    }

    def builders = [:]
    builders['ubuntu20.04'] = {
        load 'devops/ubuntu20.04/Jenkinsfile'
    }
    builders['ubuntu18.04'] = {
        load 'devops/ubuntu18.04/Jenkinsfile'
    }
    builders['windows64'] = {
        load 'devops/windows64/Jenkinsfile'
    }

    parallel builders
}
