#!/usr/bin/env groovy

node('docker_win') {
    stage('checkout') {
        cleanWs()
        checkout scm
    }
    def image
    stage('docker image') {
        VCPKG_SHA = powershell(
            script: "(git ls-remote https://github.com/Microsoft/vcpkg.git HEAD).Split()[0]",
            returnStdout: true
        ).trim()

        image = docker.build('tweaktool-win64', '--build-arg ${VCPKG_SHA} ./devops/windows64/', )
    }
    image.inside() {
        stage('build') {
            dir('build') {
                bat '"%VC_ENV_SETUP%" && powershell.exe -File "..\\devops\\windows64\\build.ps1"'
            }
        }
    }
    stage('archive') {
        dir('build') {
            zip zipFile: 'binaries.zip', archive: true, dir: 'install'
            archiveArtifacts (
                artifacts: 'tweaktool-*.exe,binaries.zip',
                fingerprint: true,
                onlyIfSuccessful: true
            )
        }
    }
}