/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "tweak.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(tweak_pb_value, tweak_pb_value, AUTO)


PB_BIND(tweak_pb_buffer_string, tweak_pb_buffer_string, AUTO)


PB_BIND(tweak_pb_buffer_raw, tweak_pb_buffer_raw, AUTO)


PB_BIND(tweak_pb_buffer_sint16, tweak_pb_buffer_sint16, AUTO)


PB_BIND(tweak_pb_buffer_sint32, tweak_pb_buffer_sint32, AUTO)


PB_BIND(tweak_pb_buffer_sint64, tweak_pb_buffer_sint64, AUTO)


PB_BIND(tweak_pb_buffer_uint16, tweak_pb_buffer_uint16, AUTO)


PB_BIND(tweak_pb_buffer_uint32, tweak_pb_buffer_uint32, AUTO)


PB_BIND(tweak_pb_buffer_uint64, tweak_pb_buffer_uint64, AUTO)


PB_BIND(tweak_pb_buffer_float, tweak_pb_buffer_float, AUTO)


PB_BIND(tweak_pb_buffer_double, tweak_pb_buffer_double, AUTO)


PB_BIND(tweak_pb_add_item, tweak_pb_add_item, AUTO)


PB_BIND(tweak_pb_subscribe, tweak_pb_subscribe, AUTO)


PB_BIND(tweak_pb_change_item, tweak_pb_change_item, AUTO)


PB_BIND(tweak_pb_remove_item, tweak_pb_remove_item, AUTO)


PB_BIND(tweak_pb_announce_features, tweak_pb_announce_features, AUTO)


PB_BIND(tweak_pb_client_node_message, tweak_pb_client_node_message, AUTO)


PB_BIND(tweak_pb_server_node_message, tweak_pb_server_node_message, AUTO)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

