/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3 */

#include "tweak.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(tweak_pb_value, tweak_pb_value, AUTO)


PB_BIND(tweak_pb_add_item, tweak_pb_add_item, AUTO)


PB_BIND(tweak_pb_subscribe, tweak_pb_subscribe, AUTO)


PB_BIND(tweak_pb_change_item, tweak_pb_change_item, AUTO)


PB_BIND(tweak_pb_remove_item, tweak_pb_remove_item, AUTO)


PB_BIND(tweak_pb_client_node_message, tweak_pb_client_node_message, AUTO)


PB_BIND(tweak_pb_server_node_message, tweak_pb_server_node_message, AUTO)



