#!/usr/bin/expect -f

# ##############################################################################
#
# Tests for command-line client of Cogent Tweak Tool.
#
# Copyright (c) 2018-2021 Cogent Embedded Inc. ALL RIGHTS RESERVED.
#
# The source code contained or described herein and all documents related to the
# source code("Software") or their modified versions are owned by Cogent
# Embedded Inc. or its affiliates.
#
# No part of the Software may be used, copied, reproduced, modified, published,
# uploaded, posted, transmitted, distributed, or disclosed in any way without
# prior express written permission from Cogent Embedded Inc.
#
# Cogent Embedded Inc. grants a nonexclusive, non-transferable, royalty-free
# license to use the Software to Licensee without the right to sublicense.
# Licensee agrees not to distribute the Software to any third-party without the
# prior written permission of Cogent Embedded Inc.
#
# Unless otherwise agreed by Cogent Embedded Inc. in writing, you may not remove
# or alter this notice or any other notice embedded in Software in any way.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# ##############################################################################

source fixture.exp

proc test_list {} {
    # Test list command
    run_command list
    expect_output "tweak_id"
    expect_output "/Zulu_.+/Zulu_.+"
}

proc test_get {} {
    # Test get command
    run_command "get /test/test"
    expect_output "\"sint32\":42"
}

# First server, then client
run_server
sleep 1
spawn $TWEAK_APP_CL -t $connection_type -u $uri
sleep 2

test_list
test_get

# Restart the server in 2 seconds
stop_server
sleep 1
run_server
sleep 2

test_list
test_get

# Restart the server in 2 seconds
stop_server
sleep 1
run_server
sleep 2

test_get

# Exit gracefully
run_command exit
expect_output eof
stop_server
