#!/usr/bin/expect -f

# ##############################################################################
#
# Tests for command-line client of Cogent Tweak Tool.
#
# Copyright (c) 2022 Cogent Embedded, Inc. ALL RIGHTS RESERVED.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
# ##############################################################################

source fixture.exp

proc test_list {} {
    # Test list command
    run_command "wait /test/tweak_jira_153_6"
    expect_output "Wait success\. Item ID = \\d+"
    run_command "list /test/tweak_jira_153_6"
    expect_output "/test/tweak_jira_153_6"
}

proc test_get {} {
    # Test get command
    run_command "wait /test/test"
    expect_output "Wait success\. Item ID = \\d+"
    run_command "get /test/test"
    expect_output "42"
}

# First server, then client

run_server
spawn $TWEAK_APP_CL -t $connection_type -u $uri -L $LOG_DIR/$argv0-tweak-app-cl.log

test_list
test_get

# Restart the server in 2 seconds
stop_server
run_server

test_list
test_get

# Restart the server in 2 seconds
stop_server
run_server

test_get

# Exit gracefully
run_command exit
expect_output eof
stop_server
